uint64 timestamp	# time since system start (microseconds)

uint32 device_id	# unique device ID for the sensor that does not change between power cycles

uint64 timestamp_sample	# time since system start (microseconds)

float32 x		# acceleration in the NED X board axis in m/s^2
float32 y		# acceleration in the NED Y board axis in m/s^2
float32 z		# acceleration in the NED Z board axis in m/s^2

float32 temperature	# temperature in degrees celsius
